services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zabe-analitcs:latest
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
    restart: unless-stopped